<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RVY637AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RVY637A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RVY637A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'errorValidator' => ['privates', 'App\\Services\\ErrorValidator', 'getErrorValidatorService', true],
            'experience' => ['privates', '.errored..service_locator.RVY637A.App\\Entity\\Experience', NULL, 'Cannot autowire service ".service_locator.RVY637A": it references class "App\\Entity\\Experience" but no such service exists.'],
        ], [
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'em' => '?',
            'errorValidator' => 'App\\Services\\ErrorValidator',
            'experience' => 'App\\Entity\\Experience',
        ]);
    }
}
